CREATE DATABASE IF NOT EXISTS `zoomio` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `zoomio`;

-- Admins table
CREATE TABLE IF NOT EXISTS `admin` (
  `ADMIN_ID` VARCHAR(100) NOT NULL PRIMARY KEY,
  `ADMIN_PASSWORD` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Seed admin
INSERT INTO `admin` (`ADMIN_ID`,`ADMIN_PASSWORD`) VALUES
('admin','admin')
ON DUPLICATE KEY UPDATE ADMIN_PASSWORD=VALUES(ADMIN_PASSWORD);

-- Users table
CREATE TABLE IF NOT EXISTS `users` (
  `EMAIL` VARCHAR(255) NOT NULL PRIMARY KEY,
  `FNAME` VARCHAR(100) NOT NULL,
  `LNAME` VARCHAR(100) NOT NULL,
  `LIC_NUM` VARCHAR(64) DEFAULT NULL,
  `PHONE_NUMBER` BIGINT DEFAULT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `GENDER` VARCHAR(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Seed users 
INSERT INTO `users` (`EMAIL`,`FNAME`,`LNAME`,`LIC_NUM`,`PHONE_NUMBER`,`PASSWORD`,`GENDER`) VALUES
('alice.w@domain.com','Alice','Walker','DL-KA-01-A100',9876540123,'Alice$ecure1','Female'),
('bob.r@domain.com','Bob','Ramirez','DL-TN-02-B200',9876545678,'BobStrong!2','Male'),
('carol.s@domain.com','Carol','Singh','DL-MH-03-C300',9876549012,'CarolPass#3','Female')
ON DUPLICATE KEY UPDATE FNAME=VALUES(FNAME), LNAME=VALUES(LNAME);

-- Cars table
CREATE TABLE IF NOT EXISTS `cars` (
  `CAR_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `CAR_NAME` VARCHAR(150) NOT NULL,
  `FUEL_TYPE` VARCHAR(50) NOT NULL,
  `CAPACITY` INT NOT NULL,
  `PRICE` INT NOT NULL,
  `CAR_IMG` VARCHAR(255) DEFAULT NULL,
  `AVAILABLE` ENUM('Y','N') DEFAULT 'Y'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Seed cars 
INSERT INTO `cars` (`CAR_NAME`,`FUEL_TYPE`,`CAPACITY`,`PRICE`,`CAR_IMG`,`AVAILABLE`) VALUES
('Ferrari F8','Petrol',2,25000,'ferrari-f8.webp','Y'),
('Lamborghini Huracan','Petrol',2,30000,'lamborghini.webp','Y'),
('Suzuki Alto Grey','Diesel',5,1200,'suzuki-alto-grey.jpg','Y'),
('Suzuki Alto Red','Petrol',5,1200,'suzuki-alto-red.jpg','Y')
ON DUPLICATE KEY UPDATE CAR_NAME=VALUES(CAR_NAME), PRICE=VALUES(PRICE);

-- Booking table
CREATE TABLE IF NOT EXISTS `booking` (
  `BOOK_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `CAR_ID` INT NOT NULL,
  `EMAIL` VARCHAR(255) NOT NULL,
  `BOOK_PLACE` VARCHAR(255) NOT NULL,
  `BOOK_DATE` DATE NOT NULL,
  `DURATION` INT NOT NULL,
  `PHONE_NUMBER` BIGINT DEFAULT NULL,
  `DESTINATION` VARCHAR(255) DEFAULT NULL,
  `RETURN_DATE` DATE DEFAULT NULL,
  `PRICE` INT DEFAULT 0,
  `BOOK_STATUS` VARCHAR(100) NOT NULL DEFAULT 'UNDER PROCESSING',
  FOREIGN KEY (`CAR_ID`) REFERENCES `cars`(`CAR_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`EMAIL`) REFERENCES `users`(`EMAIL`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Sample booking
INSERT INTO `booking` (`CAR_ID`,`EMAIL`,`BOOK_PLACE`,`BOOK_DATE`,`DURATION`,`PHONE_NUMBER`,`DESTINATION`,`RETURN_DATE`,`PRICE`,`BOOK_STATUS`) VALUES
(3,'alice.w@domain.com','Bengaluru','2025-07-15',3,9876540123,'Mysore','2025-07-18',3600,'UNDER PROCESSING')

ON DUPLICATE KEY UPDATE BOOK_STATUS=VALUES(BOOK_STATUS), PRICE=VALUES(PRICE);

-- Payment table
CREATE TABLE IF NOT EXISTS `payment` (
  `PAY_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `BOOK_ID` INT NOT NULL UNIQUE,
  `CARD_NO` VARCHAR(32) NOT NULL,
  `EXP_DATE` VARCHAR(10) NOT NULL,
  `CVV` INT NOT NULL,
  `PRICE` INT NOT NULL,
  FOREIGN KEY (`BOOK_ID`) REFERENCES `booking`(`BOOK_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Feedback 
CREATE TABLE IF NOT EXISTS `feedback` (
  `FED_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `EMAIL` VARCHAR(255) NOT NULL,
  `COMMENT` TEXT,
  FOREIGN KEY (`EMAIL`) REFERENCES `users`(`EMAIL`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
